In [ ]:
#importing libraries
import pandas as pd
import numpy as np

In [ ]:
#import dataset
df=pd.read_csv('creditcard.csv')

In [ ]:
df.head()


,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0


In [ ]:
df.dtypes


,0
Time,float64
V1,float64
V2,float64
V3,float64
V4,float64
V5,float64
V6,float64
V7,float64
V8,float64
V9,float64


In [ ]:
df.isnull().sum()

,0
Time,0
V1,0
V2,0
V3,0
V4,0
V5,0
V6,0
V7,0
V8,0
V9,0


In [ ]:
x = df.drop('Class', axis=1)
y = df['Class']

In [ ]:
x.head()


,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99


In [ ]:
y.head()

,Class
0,0
1,0
2,0
3,0
4,0


##Splitting the dataset

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3, random_state=42,stratify=y)

In [ ]:
x_train.shape,x_test.shape

((199364, 30), (85443, 30))

In [ ]:
y_train.shape,y_test.shape

((199364,), (85443,))

##Normmalising the amount column

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()
y_train = scaler.fit_transform(y_train.values.reshape(-1, 1))
y_test = scaler.transform(y_test.values.reshape(-1, 1))

#Applying SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
smote = SMOTE(random_state=42)

In [ ]:
x_train,y_train = smote.fit_resample(x_train,y_train)

In [ ]:
import pandas as pd
pd.Series(y_train.flatten()).value_counts()

,count
0.0,199020
1.0,199020


In [ ]:
x_train.shape,y_train.shape

((398040, 30), (398040,))

##Training the models

####MODEL 1  Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
#model prediction
pred = model.predict(x_test)

##MODEL EVALUATION

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

In [ ]:
print("Accuracy:",accuracy_score(y_test,pred),"\n","Confusion Matrix:\n",confusion_matrix(y_test,pred),"\n","\n",classification_report(y_test,pred),"\n","ROC AUC Score:",roc_auc_score(y_test,pred))

Accuracy: 0.9790269536416091 
 Confusion Matrix:
 [[83524  1771]
 [   21   127]] 
 
               precision    recall  f1-score   support

         0.0       1.00      0.98      0.99     85295
         1.0       0.07      0.86      0.12       148

    accuracy                           0.98     85443
   macro avg       0.53      0.92      0.56     85443
weighted avg       1.00      0.98      0.99     85443
 
 ROC AUC Score: 0.9186724373121583


###MODEL 2 RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model2 = RandomForestClassifier(n_jobs=-1,n_estimators=50,max_depth=5)

In [ ]:
model2.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=50, n_jobs=-1)

In [ ]:
pred2 = model2.predict(x_test)

##model2 evaluation

In [ ]:
print("Accuracy:",accuracy_score(y_test,pred2),"\n","Confusion Matrix:\n",confusion_matrix(y_test,pred2),"\n","\n",classification_report(y_test,pred2),"\n","ROC AUC Score:",roc_auc_score(y_test,pred2))

Accuracy: 0.9935863675198671 
 Confusion Matrix:
 [[84771   524]
 [   24   124]] 
 
               precision    recall  f1-score   support

         0.0       1.00      0.99      1.00     85295
         1.0       0.19      0.84      0.31       148

    accuracy                           0.99     85443
   macro avg       0.60      0.92      0.65     85443
weighted avg       1.00      0.99      1.00     85443
 
 ROC AUC Score: 0.9158472265571157


##MODEL3 XGBoost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
scale_pos_weight = len(y_train[y_train == 0]) / len(y_train[y_train == 1])

In [ ]:

model3 = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    n_jobs=-1,
    random_state=42,
    eval_metric='auc'
)

In [ ]:
model3.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=-1, num_parallel_tree=None, ...)

In [ ]:
pred3 = model3.predict(x_test)

##model3 evaluation

In [ ]:
print("Accuracy:",accuracy_score(y_test,pred3),"\n","Confusion Matrix:\n",confusion_matrix(y_test,pred3),"\n","\n",classification_report(y_test,pred3),"\n","ROC AUC Score:",roc_auc_score(y_test,pred3))

Accuracy: 0.9993914071369217 
 Confusion Matrix:
 [[85270    25]
 [   27   121]] 
 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     85295
         1.0       0.83      0.82      0.82       148

    accuracy                           1.00     85443
   macro avg       0.91      0.91      0.91     85443
weighted avg       1.00      1.00      1.00     85443
 
 ROC AUC Score: 0.9086372335756825


In [ ]:
prediction = model.predict(input_data)

if prediction[0] == 1:
    st.error("Fraudulent Transaction Detected 🚨")
else:
    st.success("Normal Transaction ✅")